import { CONTACT_SECTION_CONSTANTS } from '../constants/contactSection.constants';

export const contactSectionStyles = {
  overlay: `fixed inset-0 bg-black ${CONTACT_SECTION_CONSTANTS.COLORS.OVERLAY_OPACITY} flex items-center justify-center ${CONTACT_SECTION_CONSTANTS.SPACING.MODAL_PADDING} ${CONTACT_SECTION_CONSTANTS.Z_INDEX.MODAL}`,
  
  modal: `${CONTACT_SECTION_CONSTANTS.COLORS.MODAL_BACKGROUND} ${CONTACT_SECTION_CONSTANTS.LAYOUT.MODAL_BORDER_RADIUS} ${CONTACT_SECTION_CONSTANTS.LAYOUT.MODAL_PADDING} shadow-2xl w-full ${CONTACT_SECTION_CONSTANTS.LAYOUT.MODAL_MAX_WIDTH} mx-auto relative`,
  
  closeButton: `absolute top-4 right-4 ${CONTACT_SECTION_CONSTANTS.COLORS.MUTED_TEXT} hover:${CONTACT_SECTION_CONSTANTS.COLORS.PRIMARY_TEXT} transition-colors duration-${CONTACT_SECTION_CONSTANTS.TIMING.TRANSITION_DURATION} focus:outline-none`,
  
  socialContainer: `flex justify-end gap-2 ${CONTACT_SECTION_CONSTANTS.SPACING.SECTION_MARGIN}`,
  
  socialLink: `${CONTACT_SECTION_CONSTANTS.COLORS.MUTED_TEXT} hover:${CONTACT_SECTION_CONSTANTS.COLORS.PRIMARY_TEXT}`,
  
  tabContainer: `flex ${CONTACT_SECTION_CONSTANTS.COLORS.TAB_CONTAINER} rounded-xl p-1 ${CONTACT_SECTION_CONSTANTS.SPACING.SECTION_MARGIN}`,
  
  tabButton: {
    base: `flex-1 ${CONTACT_SECTION_CONSTANTS.SPACING.BUTTON_PADDING} rounded-lg text-lg font-medium transition-colors duration-${CONTACT_SECTION_CONSTANTS.TIMING.TRANSITION_DURATION}`,
    active: `${CONTACT_SECTION_CONSTANTS.COLORS.TAB_ACTIVE} ${CONTACT_SECTION_CONSTANTS.COLORS.PRIMARY_TEXT}`,
    inactive: `${CONTACT_SECTION_CONSTANTS.COLORS.SECONDARY_TEXT} hover:${CONTACT_SECTION_CONSTANTS.COLORS.PRIMARY_TEXT}`,
  },
  
  contentGrid: `grid grid-cols-1 ${CONTACT_SECTION_CONSTANTS.LAYOUT.GRID_BREAKPOINT} gap-4 ${CONTACT_SECTION_CONSTANTS.SPACING.SECTION_MARGIN}`,
  
  contactCard: `${CONTACT_SECTION_CONSTANTS.COLORS.CARD_BACKGROUND} rounded-xl ${CONTACT_SECTION_CONSTANTS.SPACING.CARD_PADDING}`,
  
  contactHeader: `flex items-center ${CONTACT_SECTION_CONSTANTS.COLORS.PRIMARY_COLOR} mb-2`,
  
  contactIcon: `${CONTACT_SECTION_CONSTANTS.SPACING.ICON_SIZE} mr-2`,
  
  contactTitle: `text-lg font-semibold ${CONTACT_SECTION_CONSTANTS.COLORS.PRIMARY_TEXT}`,
  
  contactDescription: `${CONTACT_SECTION_CONSTANTS.COLORS.SECONDARY_TEXT} text-sm mb-1`,
  
  contactLink: `${CONTACT_SECTION_CONSTANTS.COLORS.PRIMARY_COLOR} hover:underline text-sm`,
  
  formPlaceholder: `${CONTACT_SECTION_CONSTANTS.SPACING.CARD_PADDING} text-center ${CONTACT_SECTION_CONSTANTS.COLORS.SECONDARY_TEXT}`,
  
  availabilityContainer: 'mt-6 text-center',
  
  availabilityBadge: `inline-flex items-center ${CONTACT_SECTION_CONSTANTS.COLORS.AVAILABILITY_BACKGROUND} ${CONTACT_SECTION_CONSTANTS.COLORS.AVAILABILITY_TEXT} rounded-full px-4 py-2 text-sm font-medium`,
  
  availabilityDot: `${CONTACT_SECTION_CONSTANTS.SPACING.STATUS_DOT_SIZE} ${CONTACT_SECTION_CONSTANTS.COLORS.AVAILABILITY_DOT} rounded-full mr-2 animate-pulse`,
} as const;
