import { WORD_PILL_CONSTANTS } from '../constants/wordPill.constants';

export const wordPillStyles = {
  container: [
    'absolute',
    WORD_PILL_CONSTANTS.STYLING.PADDING,
    WORD_PILL_CONSTANTS.STYLING.BORDER_RADIUS,
    WORD_PILL_CONSTANTS.STYLING.TEXT_SIZE,
    'text-text-white',
    WORD_PILL_CONSTANTS.STYLING.WHITESPACE,
    WORD_PILL_CONSTANTS.STYLING.CURSOR,
    WORD_PILL_CONSTANTS.STYLING.BORDER,
    WORD_PILL_CONSTANTS.STYLING.BACKDROP,
    WORD_PILL_CONSTANTS.STYLING.SHADOW
  ].join(' '),
  
  background: WORD_PILL_CONSTANTS.COLORS.BACKGROUND_GRADIENT,
  boxShadow: WORD_PILL_CONSTANTS.COLORS.BOX_SHADOW,
  zIndex: WORD_PILL_CONSTANTS.STYLING.Z_INDEX
} as const;
